<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Indonesia',
                'official_name' => 'Republic of Indonesia',
                'code' => 'ID',
                'currency' => 'IDR',
                'currency_name' => 'Indonesian Rupiah',
                'currency_symbol' => 'Rp',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'capital' => 'Jakarta',
                'languages' => 'Indonesian',
                'flag' => 'https://flagcdn.com/w320/id.png',
                'latitude' => -0.7893,
                'longitude' => 113.9213,
                'gdp' => 1319100000000,
                'gdp_per_capita' => 4798.0,
                'inflation' => 2.84,
                'unemployment' => 5.86,
                'population' => 277534122,
                'area' => 1904569.00,
            ],
            [
                'name' => 'China',
                'official_name' => "People's Republic of China",
                'code' => 'CN',
                'currency' => 'CNY',
                'currency_name' => 'Chinese Yuan',
                'currency_symbol' => '¥',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'capital' => 'Beijing',
                'languages' => 'Mandarin Chinese',
                'flag' => 'https://flagcdn.com/w320/cn.png',
                'latitude' => 35.8617,
                'longitude' => 104.1954,
                'gdp' => 17734062645371,
                'gdp_per_capita' => 12556.0,
                'inflation' => 0.20,
                'unemployment' => 5.20,
                'population' => 1412600000,
                'area' => 9596960.00,
            ],
            [
                'name' => 'Germany',
                'official_name' => 'Federal Republic of Germany',
                'code' => 'DE',
                'currency' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'capital' => 'Berlin',
                'languages' => 'German',
                'flag' => 'https://flagcdn.com/w320/de.png',
                'latitude' => 51.1657,
                'longitude' => 10.4515,
                'gdp' => 4072191600000,
                'gdp_per_capita' => 48717.0,
                'inflation' => 2.30,
                'unemployment' => 3.00,
                'population' => 83294633,
                'area' => 357114.00,
            ],
            [
                'name' => 'Australia',
                'official_name' => 'Commonwealth of Australia',
                'code' => 'AU',
                'currency' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'currency_symbol' => 'A$',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'capital' => 'Canberra',
                'languages' => 'English',
                'flag' => 'https://flagcdn.com/w320/au.png',
                'latitude' => -25.2744,
                'longitude' => 133.7751,
                'gdp' => 1675419130000,
                'gdp_per_capita' => 64491.0,
                'inflation' => 3.60,
                'unemployment' => 3.80,
                'population' => 26461166,
                'area' => 7741220.00,
            ],
            [
                'name' => 'United States',
                'official_name' => 'United States of America',
                'code' => 'US',
                'currency' => 'USD',
                'currency_name' => 'United States Dollar',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'capital' => 'Washington, D.C.',
                'languages' => 'English',
                'flag' => 'https://flagcdn.com/w320/us.png',
                'latitude' => 37.0902,
                'longitude' => -95.7129,
                'gdp' => 25462700000000,
                'gdp_per_capita' => 76390.0,
                'inflation' => 3.40,
                'unemployment' => 3.90,
                'population' => 334914895,
                'area' => 9372610.00,
            ],
            [
                'name' => 'Japan',
                'official_name' => 'Japan',
                'code' => 'JP',
                'currency' => 'JPY',
                'currency_name' => 'Japanese Yen',
                'currency_symbol' => '¥',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'capital' => 'Tokyo',
                'languages' => 'Japanese',
                'flag' => 'https://flagcdn.com/w320/jp.png',
                'latitude' => 36.2048,
                'longitude' => 138.2529,
                'gdp' => 4231141000000,
                'gdp_per_capita' => 33806.0,
                'inflation' => 2.80,
                'unemployment' => 2.50,
                'population' => 125681593,
                'area' => 377930.00,
            ],
            [
                'name' => 'Singapore',
                'official_name' => 'Republic of Singapore',
                'code' => 'SG',
                'currency' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'currency_symbol' => 'S$',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'capital' => 'Singapore',
                'languages' => 'English, Malay, Mandarin, Tamil',
                'flag' => 'https://flagcdn.com/w320/sg.png',
                'latitude' => 1.3521,
                'longitude' => 103.8198,
                'gdp' => 466789000000,
                'gdp_per_capita' => 82807.0,
                'inflation' => 3.00,
                'unemployment' => 2.10,
                'population' => 5637022,
                'area' => 710.00,
            ],
            [
                'name' => 'United Kingdom',
                'official_name' => 'United Kingdom of Great Britain and Northern Ireland',
                'code' => 'GB',
                'currency' => 'GBP',
                'currency_name' => 'British Pound Sterling',
                'currency_symbol' => '£',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'capital' => 'London',
                'languages' => 'English',
                'flag' => 'https://flagcdn.com/w320/gb.png',
                'latitude' => 55.3781,
                'longitude' => -3.4360,
                'gdp' => 3070668350000,
                'gdp_per_capita' => 46125.0,
                'inflation' => 4.00,
                'unemployment' => 4.20,
                'population' => 67026292,
                'area' => 242900.00,
            ],
            [
                'name' => 'India',
                'official_name' => 'Republic of India',
                'code' => 'IN',
                'currency' => 'INR',
                'currency_name' => 'Indian Rupee',
                'currency_symbol' => '₹',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'capital' => 'New Delhi',
                'languages' => 'Hindi, English',
                'flag' => 'https://flagcdn.com/w320/in.png',
                'latitude' => 20.5937,
                'longitude' => 78.9629,
                'gdp' => 3385089642000,
                'gdp_per_capita' => 2389.0,
                'inflation' => 5.10,
                'unemployment' => 8.00,
                'population' => 1428627663,
                'area' => 3287590.00,
            ],
            [
                'name' => 'Malaysia',
                'official_name' => 'Malaysia',
                'code' => 'MY',
                'currency' => 'MYR',
                'currency_name' => 'Malaysian Ringgit',
                'currency_symbol' => 'RM',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'capital' => 'Kuala Lumpur',
                'languages' => 'Malay',
                'flag' => 'https://flagcdn.com/w320/my.png',
                'latitude' => 4.2105,
                'longitude' => 101.9758,
                'gdp' => 415337765000,
                'gdp_per_capita' => 12462.0,
                'inflation' => 2.50,
                'unemployment' => 3.30,
                'population' => 33600000,
                'area' => 329847.00,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
